---

- name: Download source code
  get_url: url=https://github.com/phpredis/phpredis/archive/php7.zip dest=/tmp/php7-redis.zip

- name: Extract archive
  unarchive: src=/tmp/php7-redis.zip dest=/tmp copy=no

- name: Make clean
  shell: chdir=/tmp/phpredis-php7 make clean > /dev/null
  ignore_errors: yes

- name: Phpize
  shell: chdir=/tmp/phpredis-php7 /opt/php7/bin/phpize > /dev/null

- name: Configure
  shell: chdir=/tmp/phpredis-php7 ./configure --with-php-config=/opt/php7/bin/php-config > /dev/null

- name: Make
  shell: chdir=/tmp/phpredis-php7 make > /dev/null

- name: Install
  shell: chdir=/tmp/phpredis-php7 make install > /dev/null
  become: yes