---

- name: Install libmemcached-dev
  apt: name=libmemcached-dev state=present update_cache=yes cache_valid_time=3600
  become: yes

- name: Download source code
  get_url: url=https://github.com/php-memcached-dev/php-memcached/archive/php7.zip dest=/tmp/php7-memcached.zip

- name: Extract archive
  unarchive: src=/tmp/php7-memcached.zip dest=/tmp copy=no

- name: Make clean
  shell: chdir=/tmp/php-memcached-php7 make clean > /dev/null
  ignore_errors: yes

- name: Phpize
  shell: chdir=/tmp/php-memcached-php7 /opt/php7/bin/phpize > /dev/null

- name: Configure
  shell: chdir=/tmp/php-memcached-php7 ./configure --with-php-config=/opt/php7/bin/php-config > /dev/null

- name: Make
  shell: chdir=/tmp/php-memcached-php7 make > /dev/null

- name: Install
  shell: chdir=/tmp/php-memcached-php7 make install > /dev/null
  become: yes