---

- name: install dependencies
  include_tasks: packages-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml

- name: get php version
  command: php7 --version
  register: php7cli_current
  ignore_errors: yes

- name: install php-cli
  include_tasks: php-cli.yml
  when: php7cli_current.rc != 0 or not php7cli_current.stdout | search(php7cli_version_string_match)

- include_tasks: config.yml

- include_tasks: extensions.yml

- include_tasks: default.yml
  when: php7cli_default | default(true) | bool
