---

- name: Get php version
  command: php7 --version
  register: php7cli_current
  ignore_errors: yes

- set_fact: php7cli_real_version="{{ php7cli_version | regex_replace('-\\d+$', '') }}"

- name: Install php-cli
  include: php-cli.yml
  when: php7cli_current.rc != 0 or php7cli_current.stdout.find("PHP {{ php7cli_real_version }} (cli)") == -1

- include: config.yml

- include: ext-apcu.yml

- include: ext-imagick.yml

- include: ext-igbinary.yml

- include: ext-redis.yml

- include: ext-iredis.yml

- include: default.yml
  when: php7cli_default | default(true) | bool
