---

- name: Get php version
  command: php7 --version
  register: php7cli_current
  ignore_errors: yes

- debug:
    var: php7cli_real_version

- debug:
    var: php7cli_version_string_match

- name: Install php-cli
  include: php-cli.yml
  when: php7cli_current.rc != 0 or not php7cli_current.stdout | search(php7cli_version_string_match)

- include: config.yml

- include: ext-apcu.yml

- include: ext-imagick.yml

- include: ext-igbinary.yml

- include: ext-redis.yml

- include: ext-iredis.yml

- include: ext-memcached.yml

- include: default.yml
  when: php7cli_default | default(true) | bool
